[package]
name = "yac8"
version = "0.1.0"
authors = ["halfhorst <chorst22@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
sdl2 = "0.34"
log = "0.4.8"
simple_logger = "1.6.0"
clap = "2.33"
